// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Cover                string               `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Tags                 []string             `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Post) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Post) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type OneReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneReq) Reset()         { *m = OneReq{} }
func (m *OneReq) String() string { return proto.CompactTextString(m) }
func (*OneReq) ProtoMessage()    {}
func (*OneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{1}
}

func (m *OneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneReq.Unmarshal(m, b)
}
func (m *OneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneReq.Marshal(b, m, deterministic)
}
func (m *OneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneReq.Merge(m, src)
}
func (m *OneReq) XXX_Size() int {
	return xxx_messageInfo_OneReq.Size(m)
}
func (m *OneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OneReq.DiscardUnknown(m)
}

var xxx_messageInfo_OneReq proto.InternalMessageInfo

func (m *OneReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListReq struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{2}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListReq) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

type SearchByTagsReq struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	From                 int32    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByTagsReq) Reset()         { *m = SearchByTagsReq{} }
func (m *SearchByTagsReq) String() string { return proto.CompactTextString(m) }
func (*SearchByTagsReq) ProtoMessage()    {}
func (*SearchByTagsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{3}
}

func (m *SearchByTagsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByTagsReq.Unmarshal(m, b)
}
func (m *SearchByTagsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByTagsReq.Marshal(b, m, deterministic)
}
func (m *SearchByTagsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByTagsReq.Merge(m, src)
}
func (m *SearchByTagsReq) XXX_Size() int {
	return xxx_messageInfo_SearchByTagsReq.Size(m)
}
func (m *SearchByTagsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByTagsReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByTagsReq proto.InternalMessageInfo

func (m *SearchByTagsReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchByTagsReq) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchByTagsReq) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type SimilarArticlesReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	From                 int32    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimilarArticlesReq) Reset()         { *m = SimilarArticlesReq{} }
func (m *SimilarArticlesReq) String() string { return proto.CompactTextString(m) }
func (*SimilarArticlesReq) ProtoMessage()    {}
func (*SimilarArticlesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{4}
}

func (m *SimilarArticlesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarArticlesReq.Unmarshal(m, b)
}
func (m *SimilarArticlesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarArticlesReq.Marshal(b, m, deterministic)
}
func (m *SimilarArticlesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarArticlesReq.Merge(m, src)
}
func (m *SimilarArticlesReq) XXX_Size() int {
	return xxx_messageInfo_SimilarArticlesReq.Size(m)
}
func (m *SimilarArticlesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarArticlesReq.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarArticlesReq proto.InternalMessageInfo

func (m *SimilarArticlesReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SimilarArticlesReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SimilarArticlesReq) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

type OneRes struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneRes) Reset()         { *m = OneRes{} }
func (m *OneRes) String() string { return proto.CompactTextString(m) }
func (*OneRes) ProtoMessage()    {}
func (*OneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{5}
}

func (m *OneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneRes.Unmarshal(m, b)
}
func (m *OneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneRes.Marshal(b, m, deterministic)
}
func (m *OneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneRes.Merge(m, src)
}
func (m *OneRes) XXX_Size() int {
	return xxx_messageInfo_OneRes.Size(m)
}
func (m *OneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_OneRes.DiscardUnknown(m)
}

var xxx_messageInfo_OneRes proto.InternalMessageInfo

func (m *OneRes) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type ListRes struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRes) Reset()         { *m = ListRes{} }
func (m *ListRes) String() string { return proto.CompactTextString(m) }
func (*ListRes) ProtoMessage()    {}
func (*ListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{6}
}

func (m *ListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRes.Unmarshal(m, b)
}
func (m *ListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRes.Marshal(b, m, deterministic)
}
func (m *ListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRes.Merge(m, src)
}
func (m *ListRes) XXX_Size() int {
	return xxx_messageInfo_ListRes.Size(m)
}
func (m *ListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRes proto.InternalMessageInfo

func (m *ListRes) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*OneReq)(nil), "OneReq")
	proto.RegisterType((*ListReq)(nil), "ListReq")
	proto.RegisterType((*SearchByTagsReq)(nil), "SearchByTagsReq")
	proto.RegisterType((*SimilarArticlesReq)(nil), "SimilarArticlesReq")
	proto.RegisterType((*OneRes)(nil), "OneRes")
	proto.RegisterType((*ListRes)(nil), "ListRes")
}

func init() {
	proto.RegisterFile("post/post.proto", fileDescriptor_e9e4a9952ba66d64)
}

var fileDescriptor_e9e4a9952ba66d64 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xbf, 0x92, 0x76, 0x82, 0x08, 0x1a, 0x10, 0x72, 0x5d, 0x24, 0x2c, 0x23, 0xa1, 0x1c,
	0xd0, 0x46, 0x84, 0x13, 0xc7, 0x20, 0x71, 0x2b, 0x2a, 0x72, 0x7a, 0x47, 0x8e, 0xbd, 0x0d, 0x2b,
	0xc5, 0x59, 0xb3, 0x3b, 0xad, 0x14, 0x8e, 0xfc, 0x40, 0x7e, 0x13, 0x9a, 0x5d, 0x1b, 0x42, 0x5a,
	0x09, 0x71, 0xb1, 0xde, 0xbc, 0x79, 0x33, 0xbb, 0xef, 0xad, 0x61, 0xda, 0x69, 0x4b, 0x73, 0xfe,
	0x88, 0xce, 0x68, 0xd2, 0xd9, 0xcb, 0x8d, 0xd6, 0x9b, 0xad, 0x9c, 0xbb, 0x6a, 0x7d, 0x7b, 0x33,
	0x27, 0xd5, 0x4a, 0x4b, 0x55, 0xdb, 0xf5, 0x82, 0x8b, 0x63, 0x81, 0x6c, 0x3b, 0xda, 0xfb, 0x66,
	0xf1, 0x23, 0x84, 0xf8, 0xb3, 0xb6, 0x84, 0x8f, 0x21, 0x54, 0x4d, 0x1a, 0xe4, 0xc1, 0xec, 0xac,
	0x0c, 0x55, 0x83, 0xcf, 0x20, 0x21, 0x45, 0x5b, 0x99, 0x86, 0x8e, 0xf2, 0x05, 0xe6, 0x30, 0x69,
	0xa4, 0xad, 0x8d, 0xea, 0x48, 0xe9, 0x5d, 0x1a, 0xb9, 0xde, 0x21, 0x85, 0x08, 0xf1, 0x5a, 0x37,
	0xfb, 0x34, 0x76, 0x2d, 0x87, 0x79, 0x57, 0xad, 0xef, 0xa4, 0x49, 0x13, 0xbf, 0xcb, 0x15, 0xac,
	0xbc, 0xae, 0x36, 0x36, 0x1d, 0xe5, 0x11, 0x2b, 0x19, 0xe3, 0x7b, 0x80, 0xda, 0xc8, 0x8a, 0x64,
	0xf3, 0xa5, 0xa2, 0x74, 0x9c, 0x07, 0xb3, 0xc9, 0x22, 0x13, 0xde, 0x80, 0x18, 0x0c, 0x88, 0xeb,
	0xc1, 0x61, 0x79, 0xd6, 0xab, 0x97, 0xc4, 0xa3, 0xb7, 0x5d, 0x33, 0x8c, 0x9e, 0xfe, 0x7b, 0xb4,
	0x57, 0x2f, 0xa9, 0x48, 0x61, 0x74, 0xb5, 0x93, 0xa5, 0xfc, 0x76, 0x9c, 0x42, 0xf1, 0x16, 0xc6,
	0x97, 0xca, 0x12, 0xb7, 0x10, 0x62, 0xab, 0xbe, 0x4b, 0xd7, 0x4c, 0x4a, 0x87, 0x99, 0xbb, 0x31,
	0xba, 0x75, 0x19, 0x25, 0xa5, 0xc3, 0xc5, 0x27, 0x98, 0xae, 0x64, 0x65, 0xea, 0xaf, 0x1f, 0xf6,
	0x6c, 0xe9, 0x3f, 0x46, 0x99, 0x23, 0x4e, 0x24, 0xf2, 0x89, 0x30, 0x2e, 0x2e, 0x01, 0x57, 0xaa,
	0x55, 0xdb, 0xca, 0x2c, 0x0d, 0xa9, 0x7a, 0x2b, 0xed, 0x03, 0xf7, 0xfc, 0x7d, 0x42, 0xf8, 0xc0,
	0x09, 0xd1, 0xc1, 0xe5, 0x5e, 0xf5, 0x4e, 0x2d, 0x9e, 0xfb, 0x77, 0x77, 0x3b, 0x26, 0x8b, 0x44,
	0x70, 0x51, 0x3a, 0xaa, 0x78, 0x3d, 0x98, 0xb6, 0x78, 0x01, 0x09, 0x53, 0x36, 0x0d, 0xf2, 0xe8,
	0x8f, 0xcc, 0x73, 0x8b, 0x9f, 0x01, 0x8c, 0x19, 0xad, 0xee, 0x6a, 0x3c, 0x87, 0xe8, 0x6a, 0x27,
	0x71, 0x2c, 0x7c, 0x90, 0x59, 0x0f, 0x6c, 0x71, 0x82, 0x2f, 0x20, 0xe6, 0x75, 0x78, 0x2a, 0xfa,
	0x28, 0xb3, 0x01, 0x71, 0x77, 0x06, 0xc9, 0x8a, 0xb4, 0x91, 0xe8, 0x77, 0x67, 0xcf, 0xef, 0x3d,
	0xd9, 0x47, 0xfe, 0x5d, 0x8b, 0x13, 0x7c, 0x03, 0x8f, 0x0e, 0x83, 0xc5, 0x27, 0xe2, 0x28, 0xe7,
	0xbf, 0xf6, 0x2e, 0x60, 0x7a, 0x94, 0x1b, 0x3e, 0x15, 0xf7, 0x93, 0x3c, 0x9c, 0x59, 0x8f, 0xdc,
	0x99, 0xef, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xfd, 0x77, 0xc4, 0x64, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostSvcClient is the client API for PostSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostSvcClient interface {
	One(ctx context.Context, in *OneReq, opts ...grpc.CallOption) (*OneRes, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRes, error)
	Store(ctx context.Context, in *Post, opts ...grpc.CallOption) (*empty.Empty, error)
	SearchByTags(ctx context.Context, in *SearchByTagsReq, opts ...grpc.CallOption) (*ListRes, error)
	SimilarArticles(ctx context.Context, in *SimilarArticlesReq, opts ...grpc.CallOption) (*ListRes, error)
}

type postSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPostSvcClient(cc grpc.ClientConnInterface) PostSvcClient {
	return &postSvcClient{cc}
}

func (c *postSvcClient) One(ctx context.Context, in *OneReq, opts ...grpc.CallOption) (*OneRes, error) {
	out := new(OneRes)
	err := c.cc.Invoke(ctx, "/PostSvc/One", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRes, error) {
	out := new(ListRes)
	err := c.cc.Invoke(ctx, "/PostSvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) Store(ctx context.Context, in *Post, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/PostSvc/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) SearchByTags(ctx context.Context, in *SearchByTagsReq, opts ...grpc.CallOption) (*ListRes, error) {
	out := new(ListRes)
	err := c.cc.Invoke(ctx, "/PostSvc/SearchByTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) SimilarArticles(ctx context.Context, in *SimilarArticlesReq, opts ...grpc.CallOption) (*ListRes, error) {
	out := new(ListRes)
	err := c.cc.Invoke(ctx, "/PostSvc/SimilarArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSvcServer is the server API for PostSvc service.
type PostSvcServer interface {
	One(context.Context, *OneReq) (*OneRes, error)
	List(context.Context, *ListReq) (*ListRes, error)
	Store(context.Context, *Post) (*empty.Empty, error)
	SearchByTags(context.Context, *SearchByTagsReq) (*ListRes, error)
	SimilarArticles(context.Context, *SimilarArticlesReq) (*ListRes, error)
}

// UnimplementedPostSvcServer can be embedded to have forward compatible implementations.
type UnimplementedPostSvcServer struct {
}

func (*UnimplementedPostSvcServer) One(ctx context.Context, req *OneReq) (*OneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method One not implemented")
}
func (*UnimplementedPostSvcServer) List(ctx context.Context, req *ListReq) (*ListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedPostSvcServer) Store(ctx context.Context, req *Post) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedPostSvcServer) SearchByTags(ctx context.Context, req *SearchByTagsReq) (*ListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByTags not implemented")
}
func (*UnimplementedPostSvcServer) SimilarArticles(ctx context.Context, req *SimilarArticlesReq) (*ListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimilarArticles not implemented")
}

func RegisterPostSvcServer(s *grpc.Server, srv PostSvcServer) {
	s.RegisterService(&_PostSvc_serviceDesc, srv)
}

func _PostSvc_One_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).One(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostSvc/One",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).One(ctx, req.(*OneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostSvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostSvc/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).Store(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_SearchByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).SearchByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostSvc/SearchByTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).SearchByTags(ctx, req.(*SearchByTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_SimilarArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarArticlesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).SimilarArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostSvc/SimilarArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).SimilarArticles(ctx, req.(*SimilarArticlesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostSvc",
	HandlerType: (*PostSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "One",
			Handler:    _PostSvc_One_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PostSvc_List_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _PostSvc_Store_Handler,
		},
		{
			MethodName: "SearchByTags",
			Handler:    _PostSvc_SearchByTags_Handler,
		},
		{
			MethodName: "SimilarArticles",
			Handler:    _PostSvc_SimilarArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post/post.proto",
}
